# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        
      - name: Deploy to GitHub Pages
        uses: gh-pages/deploy@v1
        with:
          remote_branch: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start WebSocket Server
        run: |
          node app.js &
          echo "WebSocket server started."
